// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: gorpc.proto

package gogameclient

import (
	"context"

	"github.com/a135422996/go-service-pb/gorpc/pb/gorpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountDeviceListReq         = gorpc.AccountDeviceListReq
	AccountDeviceListResp        = gorpc.AccountDeviceListResp
	AccountDeviceVo              = gorpc.AccountDeviceVo
	AccountListReq               = gorpc.AccountListReq
	AccountListResp              = gorpc.AccountListResp
	AccountVo                    = gorpc.AccountVo
	AreaParamListReq             = gorpc.AreaParamListReq
	AreaParamListResp            = gorpc.AreaParamListResp
	AreaParamVo                  = gorpc.AreaParamVo
	BaseReq                      = gorpc.BaseReq
	CommonResult                 = gorpc.CommonResult
	ConfigGetReq                 = gorpc.ConfigGetReq
	DeleteIdResp                 = gorpc.DeleteIdResp
	DeviceListReq                = gorpc.DeviceListReq
	DeviceListRes                = gorpc.DeviceListRes
	DeviceVo                     = gorpc.DeviceVo
	DictGetReq                   = gorpc.DictGetReq
	DictListReq                  = gorpc.DictListReq
	DictListResp                 = gorpc.DictListResp
	DictVo                       = gorpc.DictVo
	Empty                        = gorpc.Empty
	GameListReq                  = gorpc.GameListReq
	GameListRes                  = gorpc.GameListRes
	GameReq                      = gorpc.GameReq
	GameVo                       = gorpc.GameVo
	GlobalParamListReq           = gorpc.GlobalParamListReq
	GlobalParamListResp          = gorpc.GlobalParamListResp
	GlobalParamVo                = gorpc.GlobalParamVo
	I18NVo                       = gorpc.I18NVo
	Ids                          = gorpc.Ids
	Int64SelectController        = gorpc.Int64SelectController
	IntSelectController          = gorpc.IntSelectController
	NationalLanguageListReq      = gorpc.NationalLanguageListReq
	NationalLanguageListResp     = gorpc.NationalLanguageListResp
	NationalLanguageVo           = gorpc.NationalLanguageVo
	Page                         = gorpc.Page
	Page_OrderItem               = gorpc.Page_OrderItem
	ProductActionListReq         = gorpc.ProductActionListReq
	ProductActionListRes         = gorpc.ProductActionListRes
	ProductActionReq             = gorpc.ProductActionReq
	ProductActionVo              = gorpc.ProductActionVo
	ProductListReq               = gorpc.ProductListReq
	ProductListResp              = gorpc.ProductListResp
	ProductParamListReq          = gorpc.ProductParamListReq
	ProductParamListResp         = gorpc.ProductParamListResp
	ProductParamVo               = gorpc.ProductParamVo
	ProductVo                    = gorpc.ProductVo
	RelGameRankListReq           = gorpc.RelGameRankListReq
	RelGameRankListRes           = gorpc.RelGameRankListRes
	RelGameRankReq               = gorpc.RelGameRankReq
	RelGameRankVo                = gorpc.RelGameRankVo
	RelGameVpnGroupListReq       = gorpc.RelGameVpnGroupListReq
	RelGameVpnGroupListRes       = gorpc.RelGameVpnGroupListRes
	RelGameVpnGroupReq           = gorpc.RelGameVpnGroupReq
	RelGameVpnGroupVo            = gorpc.RelGameVpnGroupVo
	Request                      = gorpc.Request
	ResourceDelReq               = gorpc.ResourceDelReq
	Response                     = gorpc.Response
	StringSelectController       = gorpc.StringSelectController
	TipDelReq                    = gorpc.TipDelReq
	TipKey                       = gorpc.TipKey
	TipListReq                   = gorpc.TipListReq
	TipListResp                  = gorpc.TipListResp
	TipVo                        = gorpc.TipVo
	TransactionOperation         = gorpc.TransactionOperation
	TransactionReq               = gorpc.TransactionReq
	UpgradePkgGetReq             = gorpc.UpgradePkgGetReq
	UpgradePkgListReq            = gorpc.UpgradePkgListReq
	UpgradePkgListResp           = gorpc.UpgradePkgListResp
	UpgradePkgPlanDetailListReq  = gorpc.UpgradePkgPlanDetailListReq
	UpgradePkgPlanDetailListResp = gorpc.UpgradePkgPlanDetailListResp
	UpgradePkgPlanDetailVo       = gorpc.UpgradePkgPlanDetailVo
	UpgradePkgPlanListReq        = gorpc.UpgradePkgPlanListReq
	UpgradePkgPlanListResp       = gorpc.UpgradePkgPlanListResp
	UpgradePkgPlanVo             = gorpc.UpgradePkgPlanVo
	UpgradePkgVo                 = gorpc.UpgradePkgVo
	UpgradeResConfigGetReq       = gorpc.UpgradeResConfigGetReq
	UpgradeResConfigListReq      = gorpc.UpgradeResConfigListReq
	UpgradeResConfigListResp     = gorpc.UpgradeResConfigListResp
	UpgradeResConfigVo           = gorpc.UpgradeResConfigVo
	UpgradeResGetReq             = gorpc.UpgradeResGetReq
	UpgradeResListReq            = gorpc.UpgradeResListReq
	UpgradeResListResp           = gorpc.UpgradeResListResp
	UpgradeResPlanDetailListReq  = gorpc.UpgradeResPlanDetailListReq
	UpgradeResPlanDetailListResp = gorpc.UpgradeResPlanDetailListResp
	UpgradeResPlanDetailVo       = gorpc.UpgradeResPlanDetailVo
	UpgradeResPlanListReq        = gorpc.UpgradeResPlanListReq
	UpgradeResPlanListResp       = gorpc.UpgradeResPlanListResp
	UpgradeResPlanVo             = gorpc.UpgradeResPlanVo
	UpgradeResVo                 = gorpc.UpgradeResVo
	UserAppConfigGetReq          = gorpc.UserAppConfigGetReq
	UserAppConfigListReq         = gorpc.UserAppConfigListReq
	UserAppConfigListRes         = gorpc.UserAppConfigListRes
	UserAppConfigVo              = gorpc.UserAppConfigVo
	VpnGroupAddReq               = gorpc.VpnGroupAddReq
	VpnGroupGetReq               = gorpc.VpnGroupGetReq
	VpnGroupListReq              = gorpc.VpnGroupListReq
	VpnGroupListResp             = gorpc.VpnGroupListResp
	VpnGroupTagListReq           = gorpc.VpnGroupTagListReq
	VpnGroupTagListResp          = gorpc.VpnGroupTagListResp
	VpnGroupTagVo                = gorpc.VpnGroupTagVo
	VpnGroupVo                   = gorpc.VpnGroupVo
	VpnLocationExVo              = gorpc.VpnLocationExVo
	VpnLocationGetReq            = gorpc.VpnLocationGetReq
	VpnLocationListReq           = gorpc.VpnLocationListReq
	VpnLocationListResp          = gorpc.VpnLocationListResp
	VpnLocationServerCountReq    = gorpc.VpnLocationServerCountReq
	VpnLocationServerCountResp   = gorpc.VpnLocationServerCountResp
	VpnLocationServerCountVo     = gorpc.VpnLocationServerCountVo
	VpnLocationVo                = gorpc.VpnLocationVo
	VpnServerAddReq              = gorpc.VpnServerAddReq
	VpnServerListReq             = gorpc.VpnServerListReq
	VpnServerListResp            = gorpc.VpnServerListResp
	VpnServerLocationListReq     = gorpc.VpnServerLocationListReq
	VpnServerLocationListResp    = gorpc.VpnServerLocationListResp
	VpnServerLocationVo          = gorpc.VpnServerLocationVo
	VpnServerVo                  = gorpc.VpnServerVo
	VpnTagGetReq                 = gorpc.VpnTagGetReq
	VpnTagListReq                = gorpc.VpnTagListReq
	VpnTagListResp               = gorpc.VpnTagListResp
	VpnTagVo                     = gorpc.VpnTagVo

	GoGameClient interface {
		// 加速器游戏管理
		GameAdd(ctx context.Context, in *GameVo, opts ...grpc.CallOption) (*GameVo, error)
		GameUpdate(ctx context.Context, in *GameVo, opts ...grpc.CallOption) (*Empty, error)
		GameDel(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*Empty, error)
		GameGet(ctx context.Context, in *GameReq, opts ...grpc.CallOption) (*GameVo, error)
		GameList(ctx context.Context, in *GameListReq, opts ...grpc.CallOption) (*GameListRes, error)
		GameAll(ctx context.Context, in *Request, opts ...grpc.CallOption) (*GameListRes, error)
		// 游戏榜单关联关系
		RelGameRankAdd(ctx context.Context, in *RelGameRankVo, opts ...grpc.CallOption) (*RelGameRankVo, error)
		RelGameRankUpdate(ctx context.Context, in *RelGameRankVo, opts ...grpc.CallOption) (*Empty, error)
		RelGameRankDel(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*Empty, error)
		RelGameRankGet(ctx context.Context, in *RelGameRankReq, opts ...grpc.CallOption) (*RelGameRankVo, error)
		RelGameRankList(ctx context.Context, in *RelGameRankListReq, opts ...grpc.CallOption) (*RelGameRankListRes, error)
		// 游戏地域关联关系
		RelGameVpnGroupAdd(ctx context.Context, in *RelGameVpnGroupVo, opts ...grpc.CallOption) (*RelGameVpnGroupVo, error)
		RelGameVpnGroupUpdate(ctx context.Context, in *RelGameVpnGroupVo, opts ...grpc.CallOption) (*Empty, error)
		RelGameVpnGroupDel(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*Empty, error)
		RelGameVpnGroupGet(ctx context.Context, in *RelGameVpnGroupReq, opts ...grpc.CallOption) (*RelGameVpnGroupVo, error)
		RelGameVpnGroupList(ctx context.Context, in *RelGameVpnGroupListReq, opts ...grpc.CallOption) (*RelGameVpnGroupListRes, error)
	}

	defaultGoGameClient struct {
		cli zrpc.Client
	}
)

func NewGoGameClient(cli zrpc.Client) GoGameClient {
	return &defaultGoGameClient{
		cli: cli,
	}
}

// 加速器游戏管理
func (m *defaultGoGameClient) GameAdd(ctx context.Context, in *GameVo, opts ...grpc.CallOption) (*GameVo, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.GameAdd(ctx, in, opts...)
}

func (m *defaultGoGameClient) GameUpdate(ctx context.Context, in *GameVo, opts ...grpc.CallOption) (*Empty, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.GameUpdate(ctx, in, opts...)
}

func (m *defaultGoGameClient) GameDel(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*Empty, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.GameDel(ctx, in, opts...)
}

func (m *defaultGoGameClient) GameGet(ctx context.Context, in *GameReq, opts ...grpc.CallOption) (*GameVo, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.GameGet(ctx, in, opts...)
}

func (m *defaultGoGameClient) GameList(ctx context.Context, in *GameListReq, opts ...grpc.CallOption) (*GameListRes, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.GameList(ctx, in, opts...)
}

func (m *defaultGoGameClient) GameAll(ctx context.Context, in *Request, opts ...grpc.CallOption) (*GameListRes, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.GameAll(ctx, in, opts...)
}

// 游戏榜单关联关系
func (m *defaultGoGameClient) RelGameRankAdd(ctx context.Context, in *RelGameRankVo, opts ...grpc.CallOption) (*RelGameRankVo, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameRankAdd(ctx, in, opts...)
}

func (m *defaultGoGameClient) RelGameRankUpdate(ctx context.Context, in *RelGameRankVo, opts ...grpc.CallOption) (*Empty, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameRankUpdate(ctx, in, opts...)
}

func (m *defaultGoGameClient) RelGameRankDel(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*Empty, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameRankDel(ctx, in, opts...)
}

func (m *defaultGoGameClient) RelGameRankGet(ctx context.Context, in *RelGameRankReq, opts ...grpc.CallOption) (*RelGameRankVo, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameRankGet(ctx, in, opts...)
}

func (m *defaultGoGameClient) RelGameRankList(ctx context.Context, in *RelGameRankListReq, opts ...grpc.CallOption) (*RelGameRankListRes, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameRankList(ctx, in, opts...)
}

// 游戏地域关联关系
func (m *defaultGoGameClient) RelGameVpnGroupAdd(ctx context.Context, in *RelGameVpnGroupVo, opts ...grpc.CallOption) (*RelGameVpnGroupVo, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameVpnGroupAdd(ctx, in, opts...)
}

func (m *defaultGoGameClient) RelGameVpnGroupUpdate(ctx context.Context, in *RelGameVpnGroupVo, opts ...grpc.CallOption) (*Empty, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameVpnGroupUpdate(ctx, in, opts...)
}

func (m *defaultGoGameClient) RelGameVpnGroupDel(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*Empty, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameVpnGroupDel(ctx, in, opts...)
}

func (m *defaultGoGameClient) RelGameVpnGroupGet(ctx context.Context, in *RelGameVpnGroupReq, opts ...grpc.CallOption) (*RelGameVpnGroupVo, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameVpnGroupGet(ctx, in, opts...)
}

func (m *defaultGoGameClient) RelGameVpnGroupList(ctx context.Context, in *RelGameVpnGroupListReq, opts ...grpc.CallOption) (*RelGameVpnGroupListRes, error) {
	client := gorpc.NewGoGameClientClient(m.cli.Conn())
	return client.RelGameVpnGroupList(ctx, in, opts...)
}
